# Signal generation
# For each company (ticker) mentioned across today's articles, aggregate the LLM-assigned directions
# into a single bullish/bearish/neutral signal using a severity-weighted vote.
# FinBERT conviction (sentiment_score) is kept out of direction and used only in the confidence formula.
# Output: one Signal per ticker, ready to feed into the LangGraph pipeline.

from pydantic import BaseModel, Field
from typing import Literal
from datetime import datetime
from loguru import logger

class Signal(BaseModel):
    entity: str
    ticker: str
    signal: Literal['bullish', 'bearish', 'neutral']
    confidence: float = Field(ge=0, le=1)
    evidence: list[str]
    timestamp: datetime

class ArticleSignal(BaseModel):
    direction: Literal["bullish", "bearish", "neutral"]
    sentiment_score: float = Field(..., ge=-1.0, le=1.0)   # FinBERT conviction — used for confidence only
    severity_weight: float = Field(default=0.3, ge=0.0, le=1.0)  # low=0.3, medium=0.6, high=1.0

DIRECTION_VALUE: dict[str, float] = {"bullish": 1.0, "bearish": -1.0, "neutral": 0.0}
SEVERITY_WEIGHT: dict[str, float] = {"low": 0.3, "medium": 0.6, "high": 1.0}

BULLISH_THRESHOLD = 0.2
BEARISH_THRESHOLD = -0.2


def aggregate_direction(signals: list[ArticleSignal]) -> tuple[str, float]:
    total_weight = sum(DIRECTION_VALUE[s.direction] * s.severity_weight for s in signals)
    total_severity = sum(s.severity_weight for s in signals)
    aggr_severity_weight = total_weight / total_severity if total_severity else 0.0

    if aggr_severity_weight > BULLISH_THRESHOLD:
        aggr_direction = "bullish"
    elif aggr_severity_weight < BEARISH_THRESHOLD:
        aggr_direction = "bearish"
    else:
        aggr_direction = "neutral"

    return aggr_direction, aggr_severity_weight


def _compute_signal(ticker: str, name: str, signals: list[ArticleSignal]) -> Signal:
    aggr_direction, aggr_severity = aggregate_direction(signals)

    # by doing s.sentiment_score * DIRECTION_VALUE[aggr_direction]
    # we are ensuring the confidense gets enhanced if the sentiment score and aggr_direction
    #are both of the same sign (neg and neg would become pos), (pos, pos is always pos), 
    # but (neg,pos will become neg) -- which indicates a conflict in the event direction and 
    # the sentiment generated by finBert.

    avg_finbert_alignment = sum(s.sentiment_score * DIRECTION_VALUE[aggr_direction] for s in signals) / len(signals)
    article_coverage_score = min(len(signals) / 10, 1.0)  # 10+ articles = full coverage score
    confidence = max(0.0, min(0.4 * avg_finbert_alignment + 0.3 * article_coverage_score + 0.3 * abs(aggr_severity), 1.0))

    direction_counts = {label: sum(1 for s in signals if s.direction == label) for label in DIRECTION_VALUE}
    article_breakdown = ", ".join(f"{count} {label}" for label, count in direction_counts.items() if count > 0)
    finbert_verdict = "confirmed" if avg_finbert_alignment > 0 else "conflicted with"

    evidence = [
        f"{article_breakdown} across {len(signals)} article(s) — severity-weighted vote resolved to {aggr_direction}",
        f"FinBERT language {finbert_verdict} the {aggr_direction} signal (alignment score: {avg_finbert_alignment:.2f})",
        f"direction consensus strength: {abs(aggr_severity):.2f} (threshold: ±{BULLISH_THRESHOLD})",
    ]

    logger.debug(f"[{ticker}] {aggr_direction} | confidence={confidence:.2f} | articles={len(signals)}")

    return Signal(
        entity=name,
        ticker=ticker,
        signal=aggr_direction,
        confidence=round(confidence, 3),
        evidence=evidence,
        timestamp=datetime.utcnow(),
    )

def generate_signals(articles: list[dict]) -> list[Signal]:
    logger.info(f"Grouping {len(articles)} articles by ticker...")

    signals_for_entity: dict[str, list[ArticleSignal]] = {}
    ticket_entity_dict: dict[str, str] = {}

    for article in articles:
        for entity in article.get("entities", []):
            ticker = entity.get("ticker")
            if not ticker:
                continue

            article_signal = ArticleSignal(
                direction=article.get("direction", "neutral"),
                sentiment_score=article.get("sentiment", 0.0),
                severity_weight=SEVERITY_WEIGHT.get(article.get("severity", "low"), 0.3),
            )
            signals_for_entity.setdefault(ticker, []).append(article_signal)
            ticket_entity_dict.setdefault(ticker, entity.get("name", ticker))

    logger.info(f"Grouped into {len(signals_for_entity)} tickers: {list(signals_for_entity.keys())}")

    results = [
        _compute_signal(ticker, ticket_entity_dict[ticker], article_signals)
        for ticker, article_signals in signals_for_entity.items()
    ]
    logger.info(f"Generated {len(results)} signals.")
    return results
